skip_clone: false

steps:
  build:
    when:
      branch: []
      event: []
    image: alpine
    commands:
      - apk add --no-cache build-base alpine-sdk gcc go curl-dev openssl-dev ncurses-dev
      - make
